version: 0.0
os: linux

files:
  - source: deployment/Finsmart_Finances-0.0.1-SNAPSHOT.jar
    destination: /opt/finsmart/
  - source: deployment/frontend-build/
    destination: /opt/finsmart/frontend/

hooks:
  ApplicationStop:
    - location: deployment/scripts/stop.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: deployment/scripts/before_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: deployment/scripts/start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: deployment/scripts/validate.sh
      timeout: 30
      runas: root
